### PR TITLE
Enable MPI settings for parallel verification tests

### PR DESCRIPTION
**Pull request by RMeli**
```bash
spack build-env sirius +cuda +fortran +scalapack +tests -- bash

cmake \
    -DUSE_CUDA=on -DCMAKE_CUDA_ARCHITECTURES=89 \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DUSE_MEMORY_POOL=off \
    -DUSE_SCALAPACK=on \ 
    -DBUILD_TESTING=on \
    -DMPIEXEC_EXECUTABLE=mpiexec \
    -DMPIEXEC_NUMPROC_FLAG="-n" \
    -DMPIEXEC_MAX_NUMPROCS=4 \
    ..

make -j 6

export OMP_NUM_THREADS=6
ctest
```

---

```text
100% tests passed, 0 tests failed out of 153

Label Time Summary:
integration_test cpu_band_parallel       = 230.57 sec*proc (24 tests)
integration_test cpu_serial              = 221.24 sec*proc (24 tests)
integration_test gpu_band_parallel       = 544.59 sec*proc (24 tests)
integration_test gpu_k_point_parallel    = 218.36 sec*proc (24 tests)
integration_test gpu_serial              = 204.90 sec*proc (24 tests)

Total Test time (real) = 1445.67 sec
```

### CODE REVIEW

**Comment by simonpintarelli** [comment]
cscs-ci run default

**Comment by electronic-structure** [comment]
I need to add you to cicd white list,I'll do it tomorrow

**Comment by RMeli** [comment]
cscs-ci run default

**Comment by RMeli** [comment]
I changed this PR in a way that is does not interfere with CI. Users can now use `-DMPIRUN` to specify how to run MPI tests via `ctest`.

```
cmake \
    -DUSE_CUDA=on -DCMAKE_CUDA_ARCHITECTURES=89 \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DUSE_MEMORY_POOL=off \
    -DUSE_SCALAPACK=on \ 
    -DBUILD_TESTING=on \
    -DMPIRUN="mpiexec -n 4" \
    ..

make -j 6

export OMP_NUM_THREADS=6
ctest
```

Additionally, GPU tests are enabled only if `USE_CUDA` or `USE_ROCM` are set.

**Review by toxa81 — APPROVED** [review]
LGTM!

**Comment by toxa81** [comment]
@simonpintarelli If it's OK to merge, I'll do it

**Pull request merged**
