### PR TITLE
Context the hubbard section to the new input scheme

### PR DESCRIPTION
**Pull request by mtaillefumier**
Really nothing ground breaking here. The hubbard input info are using the new input scheme.

### CODE REVIEW

**Comment by toxa81** [comment]
Next step is actually to switch to config.hpp parser in parsing the Hubbard input and get rid of input.cpp. If something is updated in the JSON schema, the config.hpp should be updated by `python ../../apps/utils/gen_input_struct.py > config.hpp`

**Comment by mtaillefumier** [comment]
Ok. Do not merge this then. I want to recheck everything and take into account what you are indicating.

**Comment by mtaillefumier** [comment]
I kept the json structure intact but add to modify the input.cpp to fit the scheme.

**Comment by toxa81** [comment]
Hi @mtaillefumier ! Do we have a use case for `projection_method=file`. If not, I propose to deprecate it until the real need to read Hubbard WFs from the file emerges.

**Comment by mtaillefumier** [comment]
go ahead nuke it. I do not think even QE uses this option.

**Pull request merged**
