### PR TITLE
[release] v7.6.0

### PR DESCRIPTION
**Pull request by toxa81**
TODO:
 - [x] check that spack recipe is up-to-date; as soon as we tag a new version, it should be added to spack recipe and pushed to the main spack repo @simonpintarelli @RMeli 
 - [x] merge pending PRs (https://github.com/electronic-structure/SIRIUS/pull/1011)
 - [x] and this PR (https://github.com/electronic-structure/SIRIUS/pull/1015)
 - [x] check that cp2k works and also UPF-v2 files can be used in cp2k input @mtaillefumier 
 - [ ] any other small changes that can be incorporated?

### CODE REVIEW

**Comment by mtaillefumier** [comment]
cp2k is ready for the new release. the toolchain is updated as well. Just need to update the spack recipe

**Comment by abussy** [comment]
It would be nice if we squeeze PR #1016 in this release. We are getting close to a first integration of SIRIUS in DFTK, and the changes to the API will need to be officially released in order to create a `SIRIUS.jl` package.

**Review by mtaillefumier — APPROVED** [review]
I am good with it as soon as this PR is ready for merging. I will update cp2k build system after the tag is created.

**Review by RMeli — APPROVED** [review]
Happy to help with the Spack package(s) once the release is done.

**Review by simonpintarelli — APPROVED** [review]
I've added an update related to spla (copied from spack upstream). The rest looks good to me.

**Pull request merged**
