### PR TITLE
Fix for the stress and forces on GPU

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
@haampie do you know, why GPU parallel run failed?
```
ERROR: Job failed (system failure): unknown Custom executor executable exit code 143; executable execution terminated with: exit status 143
```

**Comment by haampie** [comment]
Due to time limit it says a bit up in the logs

**Comment by toxa81** [comment]
Ah! I see now.

**Comment by haampie** [comment]
Just to collect the reports:

```
20/20 Test #126: sirius.scf_test20_cpu_band_parallel ...   Passed   83.34 sec
20/20 Test #125: sirius.scf_test20_cpu_serial .....   Passed   84.68 sec
20/20 Test #123: sirius.scf_test20_gpu_band_parallel ...   Passed  581.19 sec
20/20 Test #124: sirius.scf_test20_gpu_k_point_parallel ...   Passed  194.81 sec
20/20 Test #122: sirius.scf_test20_gpu_serial .....   Passed  202.13 sec
```

Seems something's not really working great for the gpu tests...

**Comment by toxa81** [comment]
Ouch! My refactoring :) I'll fix it

**Comment by haampie** [comment]
So, excellent PR to share a sneak preview of the benchmark feature: https://github.com/haampie/SIRIUS-bench-reports/tree/master/cec8cbfd14a8c81a238f6b8e8163f5955b8ecb39_vs_495e097f8fb7cb2be32f3783e9a2314d02bcfd52 (develop -> this PR).

**Comment by haampie** [comment]
Let me test the benchmark feature here.

@electronic-structure run

**Comment by electronic-structure** [comment]
Benchmark started with the following settings:

```json
{
    "type": "compare",
    "reference": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "cec8cbfd14a8c81a238f6b8e8163f5955b8ecb39"
    },
    "current": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "647643e79c91101edea17dbd509be559f0e7531c"
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "issue": 569,
        "type": "pr"
    }
}

```

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/haampie/SIRIUS-bench-reports/tree/master/cec8cbfd14a8c81a238f6b8e8163f5955b8ecb39_vs_647643e79c91101edea17dbd509be559f0e7531c/

**Comment by haampie** [comment]
@toxa81: can you add a relevant benchmark to https://gitlab.com/cscs-ci/electronic-structure/benchmarking/-/tree/master/benchmarks? It's as simple as adding a new folder, but do note that you could/should add a variables.yaml file to configure slurm: https://gitlab.com/cscs-ci/electronic-structure/benchmarking/-/blob/master/benchmarks/Si63Ge/variables.yaml

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/haampie/SIRIUS-bench-reports/tree/master/cec8cbfd14a8c81a238f6b8e8163f5955b8ecb39_vs_647643e79c91101edea17dbd509be559f0e7531c/

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/haampie/SIRIUS-bench-reports/tree/master/cec8cbfd14a8c81a238f6b8e8163f5955b8ecb39_vs_647643e79c91101edea17dbd509be559f0e7531c/

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/haampie/SIRIUS-bench-reports/tree/master/cec8cbfd14a8c81a238f6b8e8163f5955b8ecb39_vs_647643e79c91101edea17dbd509be559f0e7531c/

**Comment by toxa81** [comment]
Something is not right. I can't run, for example, test15 on Daint with my custom build. CI can run the full pipeline, bit not the github action.

**Comment by toxa81** [comment]
TODO: LDA+U matrix is not symmetrized

**Comment by toxa81** [comment]
Hi @mtaillefumier ! Can you please have a look at the PR?

**Comment by haampie** [comment]
Let me just fire up another performance test vs `develop`:

@electronic-structure run

```yaml
spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/485a653</code> submitted:</summary>

```json
{
    "id": "08a5c5ef-d7d7-4976-88cb-a4ffa6988bb4",
    "reference": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "58f31ed08f2b4e9e6d289f9ed116027f00413e03",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "8cf25a48a521cee28df94fe46e001c67fed20f54",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 569
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 08a5c5ef-d7d7-4976-88cb-a4ffa6988bb4
```

**Comment by mtaillefumier** [comment]
This PR is perfectly fine. Restructuring the hubbard part was necessary for U+V. So if the PR passes all tests, just merge it. We can continue work on it afterwards

**Comment by electronic-structure** [comment]
Report for `benchmarks/485a6539` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/21/8cf25a4_vs_58f31ed-485a6539/

```diff
  Si63Ge ───────────────────  71.73 s  →  71.17 s   (-0.77%)
  Au-surf ────────────────── 132.63 s  → 132.29 s   (-0.25%)
  SiO2-ANA-kpoint-parallel ─ 133.62 s  → 130.66 s   (-2.22%)
  SiO2-ANA-band-parallel ─── 242.76 s  → 242.12 s   (-0.27%)
```

**Pull request merged**
