### PR TITLE
[WIP] Mixed precition DFT

### PR DESCRIPTION
**Pull request by toxa81**
Done templating
* Wave_functions
* Beta_projectors
* K_point 
* Hamiltonian
* Q- and D- operators

### CODE REVIEW

**Comment by toxa81** [comment]
The FP32 code should be conditional. I propose this change in all similar cases. From
``` 
   void update()
    {
        /* update k-points */
        for (int ikloc = 0; ikloc < spl_num_kpoints().local_size(); ikloc++) {
            int ik = spl_num_kpoints(ikloc);
            kpoints_[ik]->update();
#ifdef USE_FP32
            kpoints_float_[ik]->update();
#endif
        }
    }
    ```
    to
    ```
       void update()
    {
        /* update k-points */
        for (int ikloc = 0; ikloc < spl_num_kpoints().local_size(); ikloc++) {
            int ik = spl_num_kpoints(ikloc);
            kpoints_[ik]->update();
#ifdef USE_FP32
            if (ctx_.cfg().parameters().precision() == "fp32") {
                 kpoints_float_[ik]->update();
           }
#endif
        }
    }
    ```
    
    or even better
    ```
     if (ctx_.cfg().parameters().precision() == "mixed" || ctx_.cfg().parameters().precision() == "fp64")  {
        call_double_code();
     }
    if (ctx_.cfg().parameters().precision() == "mixed" || ctx_.cfg().parameters().precision() == "fp32")  {
       call_float_code();
   }
```

**Comment by toxa81** [comment]
the .get() method of K_point_set needs more template magic. Now I have
```
error: cannot convert 'std::unique_ptr<sirius::K_point<float> >::pointer' {aka 'sirius::K_point<float>*'} to 'sirius::K_point<double>*' in return
```

**Comment by manhin321** [comment]
In SDDK/hdf5_tree.hpp , we are missing the type_wrapper for std::complex<float> but I can not find which H5T type would fit it in this context 

```
template<>
struct hdf5_type_wrapper<float>
{
    static hid_t type_id()
    {
        return H5T_NATIVE_FLOAT;
    }
};

template<>
struct hdf5_type_wrapper<double>
{
    static hid_t type_id()
    {
        return H5T_NATIVE_DOUBLE;
    }
};

template<>
struct hdf5_type_wrapper<std::complex<double>>
{
    static hid_t type_id()
    {
        return H5T_NATIVE_LDOUBLE;
    }
};
```

**Comment by manhin321** [comment]
> The FP32 code should be conditional. I propose this change in all similar cases. From
> 
> ```
>    void update()
>     {
>         /* update k-points */
>         for (int ikloc = 0; ikloc < spl_num_kpoints().local_size(); ikloc++) {
>             int ik = spl_num_kpoints(ikloc);
>             kpoints_[ik]->update();
> #ifdef USE_FP32
>             kpoints_float_[ik]->update();
> #endif
>         }
>     }
> ```
> 
> to
> 
> ```
>        void update()
>     {
>         /* update k-points */
>         for (int ikloc = 0; ikloc < spl_num_kpoints().local_size(); ikloc++) {
>             int ik = spl_num_kpoints(ikloc);
>             kpoints_[ik]->update();
> #ifdef USE_FP32
>             if (ctx_.cfg().parameters().precision() == "fp32") {
>                  kpoints_float_[ik]->update();
>            }
> #endif
>         }
>     }
> ```
> 
> or even better
> 
> ```
>     if (ctx_.cfg().parameters().precision() == "mixed" || ctx_.cfg().parameters().precision() == "fp64")  {
>        call_double_code();
>     }
>    if (ctx_.cfg().parameters().precision() == "mixed" || ctx_.cfg().parameters().precision() == "fp32")  {
>       call_float_code();
>   }
> ```

For this change, Should we consider to store a separate K_point_base class in K_point_set class, so that the weight, coordinates, etc. can be obtained even if the fp64 type K_point_class is not constructed in the K_point_set class?

**Comment by toxa81** [comment]
For HDF5: it doesn't support complex types. Complex is packed as two consecutive doubles by the host code

**Comment by toxa81** [comment]
There is now merge conflict and more deep issues with fp32/fp64 k-point energies. I'm going to move the band energies into k_point_set class and make them only fp64. When Davidson<fp32> returns eigen-values, they will be copied to fp64 values.

**Comment by toxa81** [comment]
@manhin321 I started to put some order in the code.
* all non-performance critical variables, such as atom positions, G+k vector coordinates, k-point coordinates, weights, band energies and occupancies should remain in fp64
* only performance critical objects should have fp32 support. For now this are the wave-functions and Hamiltonian

**Comment by toxa81** [comment]
Stand-alone function for Davidson iterative solver should be a next step

**Comment by toxa81** [comment]
@haampie 
We crash clang
```
722    clang: error: unable to execute command: Segmentation fault (core d
            umped)
  >> 723    clang: error: clang frontend command failed due to signal (use -v t
```

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
@haampie is there a way to update clang on the CI/CD?

**Comment by haampie** [comment]
Yeah, let me just bump the base images to ubuntu 20.04, then we have clang 10

**Comment by toxa81** [comment]
Why `clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)`

**Comment by toxa81** [comment]
@haampie `sirius@develop%clang@6.0.0` it's Clang of spack which is 6.0

**Comment by haampie** [comment]
Yeah, it's the default system clang version on ubuntu 18.04. I've added https://github.com/electronic-structure/SIRIUS/commit/2b07af779d2f9669b193332631ff4d374178de8a that drops all mentions of compiler versions, but unfortunately spack doesn't autodetect a fortran compiler for clang by default, so rebuilding dependencies failed: https://gitlab.com/cscs-ci/electronic-structure/build-spack-images/-/jobs/1434876395#L1905 :(. Let me fix that now.

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
@manhin321 the Davidson<fp32> diagonalization seems to be working for real systems. I tried test01 (SrVO3) and was able to converge it with accuracy parameters, adjusted for fp32

**Comment by mtaillefumier** [comment]
I have no objection so far.

**Review by simonpintarelli — APPROVED** [review]
This is fine for me.

**Pull request merged**
