### PR TITLE
print non local occupation matrix

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
* better output of nearest neighbors
* add non-local part of the occupation matrix
* print the non-local part
* test26 is the example of the non-local Hubbard input

**Comment by mtaillefumier** [comment]
looks good to me so far. I saw you split the local and non local occupations.

**Comment by toxa81** [comment]
Next PR will be about computing the non-local part of the occupation matrix.

**Comment by mtaillefumier** [comment]
that's perfectly fine with me. I will review it.

**Pull request merged**
