### PR TITLE
Tweaks to API generation

### PR DESCRIPTION
**Pull request by toxa81**
Allow `pass by value` for the Fortran API.
This is now possible `call sirius_create_context(MPI_COMM_WORLD, handler)`

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
Do you know why CMake doesn't pick it? It knows that it is a Fortran/C++ project. It has discovered MPI library and now it needs to link with fortran part

**Comment by haampie** [comment]
So we're adding the Fortran sources to the sirius cmake target, maybe a `$<$<BOOL:${CREATE_FORTRAN_BINDINGS}>:MPI::MPI_FORTRAN>` should be added in src/CMakeLists.txt?

**Comment by toxa81** [comment]
> So we're adding the Fortran sources to the sirius cmake target, maybe a `$<$<BOOL:${CREATE_FORTRAN_BINDINGS}>:MPI::MPI_FORTRAN>` should be added in src/CMakeLists.txt? There's only a MPI_CXX there right now

let's consult with @AdhocMan

**Comment by simonpintarelli** [comment]
I think also, because of the `use mpi`, we need to link with mpi fortran as Harmen said.

**Comment by AdhocMan** [comment]
> I think also, because of the `use mpi`, we need to link with mpi fortran as Harmen said.

I agree, that the error occurs because of calling mpi functions in the fortran test executables. I'd suggest to only link the fortran executables directly to `MPI::MPI_FORTRAN`, since the sirius library itself doesn't require it.

**Comment by toxa81** [comment]
bors try

**Pull request merged**
