### PR TITLE
single file for Fortran API

### PR DESCRIPTION
**Pull request by toxa81**
Modify python script to write a single `sirius.f90` file with Fortran API.

### CODE REVIEW

**Review by mtaillefumier — APPROVED** [review]

**Comment by mtaillefumier** [comment]
Simplifications are always welcome. Do you want me to test with cp2k ?

**Comment by toxa81** [comment]
> Simplifications are always welcome. Do you want me to test with cp2k ?

It should not brake anything, but a simple test is welcomed.

**Comment by mtaillefumier** [comment]
I will do it then.

**Comment by mtaillefumier** [comment]
it is good to go. Compilation and runtests passed without any problem.

**Pull request merged**
