### PR TITLE
fix nlcglib spec in ci

### PR DESCRIPTION
**Pull request by simonpintarelli**

### CODE REVIEW

**Comment by haampie** [comment]
bors merge

**Comment by haampie** [comment]
bors merge

**Comment by simonpintarelli** [comment]
bors merge

**Comment by simonpintarelli** [comment]
bors merge

**Comment by haampie** [comment]
i think the cuda arch issue is a package.py issue? also it seems like it's building/using cmake 3.18.x now, for which the cmake script is a bit different

**Pull request merged**
