### PR TITLE
Configure Jenkins to push build logs to another repo

### PR DESCRIPTION
**Pull request by haampie**
The idea is to push the build artifacts / logs to another GitHub repo.

TODO:

- [x] configure the bot / user that pushes from Jenkins
- [x] move the repo under this org.

### CODE REVIEW

**Comment by haampie** [comment]
@simonpintarelli I think I might need push access to this repo in order to be able to test the Jenkins config from the PR itself, otherwise Jenkins discards it as untrusted and uses the old Jenkinsfile.

**Comment by haampie** [comment]
Ok, so it seems there is a security problem when interpolating `SSH_KEY_PATH` as a Groovy variable instead of the shell env variable (ref https://jenkins.io/doc/pipeline/steps/credentials-binding/), should fix that.

A nice feature to use instead of the approach above is `unarchive` s.t. artifacts are specified only once. Unfortunately Jenkins is lacking conditional `post` steps, so for now I would have to wrap the upload & comment feature in a script block.

**Comment by simonpintarelli** [comment]
> @simonpintarelli I think I might need push access to this repo in order to be able to test the Jenkins config from the PR itself, otherwise Jenkins discards it as untrusted and uses the old Jenkinsfile.

@haampie You need write access to the electronic-structure/SIRIUS, otherwise you PR won't be built by jenkins. Seems Anton gave you the permissions already.

**Comment by haampie** [comment]
Ok, thanks, running it again now with the current Jenkinsfile.

**Comment by haampie** [comment]
Seems like the vm runs an ancient version of git :/

**Pull request closed without merging**
