### PR TITLE
Fix/beta projectors for exact diag

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try-

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try-

**Comment by toxa81** [comment]
bors try

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors try-

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Pull request merged**
