### PR TITLE
Add hubbard ortho case for forces

### PR DESCRIPTION
**Pull request by mtaillefumier**
Hubbard U : Forces for both ortho / non-ortho case works now
Need to test the U+V case but the only possible issue will come from the forces.cpp

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
@mtaillefumier Hubbard stress is wrong for test22 for GPU cases. CPU passes

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try-

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
Summary of changes:
* bulk of the code for ortho-atomic lda+u stress and forces is refactored
* obsolete functions are removed

@mtaillefumier can you please give a quick look, then it's good to be merged; the (possible) fixes for lda+u+v will be addressed in another PR.

**Comment by mtaillefumier** [comment]
you can merge it if it gives the same answer than QE which it most probably does. The V correction will only impact the forces.cpp and stress.cpp not the calculation of the occupation numbers.

**Pull request merged**
