### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Comment by e-kwsm** [comment]
I wonder why different variables are used to search LibVDWXC: https://github.com/electronic-structure/SIRIUS/blob/8725bb9bc56d7655df9e02b2a511cb63def29d85/cmake/modules/FindLibVDWXC.cmake#L14-L16 and https://github.com/electronic-structure/SIRIUS/blob/8725bb9bc56d7655df9e02b2a511cb63def29d85/cmake/modules/FindLibVDWXC.cmake#L24-L26

Backward compatibility?

**Comment by simonpintarelli** [comment]
@e-kwsm thank you for fixing the typos. 

Variable names for VDWXC are fixed in https://github.com/electronic-structure/SIRIUS/pull/482

**Comment by simonpintarelli** [comment]
@toxa81 can we merge?

**Comment by e-kwsm** [comment]
Why closed?

**Comment by toxa81** [comment]
It was fixed in another pull request (https://github.com/electronic-structure/SIRIUS/pull/482)

**Comment by e-kwsm** [comment]
#482 has no overlap with this PR.

**Comment by toxa81** [comment]
@simonpintarelli Simon, can you please have a look at this PR? Why #482 is not fixing this?

**Comment by simonpintarelli** [comment]
@toxa81 It fixes a couple typos (swapped characters).#482 just fixed libvdwxc, I think we should merge it.

**Pull request merged**
