### PR TITLE
Update to clang format 18

### PR DESCRIPTION
**Pull request by simonpintarelli**
- Update `clang-format` in github actions from 17 to 18
- reformat the code (didn't manage to tweak the option such that there is no diff between the two versions)

### CODE REVIEW

**Comment by toxa81** [comment]
It's OK to re-apply the format, but it should be done in a standalone PR.

**Comment by simonpintarelli** [comment]
I'm trying to figure out the options to make the least changes in a reformat.

**Comment by simonpintarelli** [comment]
@mtaillefumier could you please check if this is consistent with clang-format of llvm 17?

**Comment by mtaillefumier** [comment]
I will do that right away

**Review by mtaillefumier — APPROVED** [review]
I applied the formating script locally and no change to the files. This seems to fix the issue I had last week. Thanks.

Approved

**Review by toxa81 — APPROVED** [review]
OK to me

**Pull request merged**
