### PR TITLE
develop -> master

### PR DESCRIPTION
**Pull request by haampie**
Not meant to merge right away, but rather to run benchmarks.

### CODE REVIEW

**Comment by electronic-structure** [comment]
Benchmark started with the following settings:

```json
{
    "reference": {
        "spec": "sirius@6.5.7 +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e"
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a923c3c8853d846138a8b9a9c096494004b8d208"
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/13/a923c3c_vs_a24d674/

```diff
  Si63Ge ───────────────────  76.83 s  →  71.53 s   (-6.89%)
+ SiO2-ANA-kpoint-parallel ─ 176.38 s  → 133.76 s  (-24.16%)
+ SiO2-ANA-band-parallel ─── 290.69 s  → 245.96 s  (-15.39%)
```

**Comment by haampie** [comment]
@electronic-structure run

```yaml
reference:
  spec: sirius@6.5.7 +scalapack
current:
  spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/a0a0af4</code> submitted:</summary>

```json
{
    "id": "4f9f6d54-69d7-48df-8818-4114aabf7677",
    "reference": {
        "spec": "sirius@6.5.7 +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a923c3c8853d846138a8b9a9c096494004b8d208",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 4f9f6d54-69d7-48df-8818-4114aabf7677
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/a0a0af43` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/19/a923c3c_vs_a24d674-a0a0af43/

```diff
  Si63Ge ───────────────────  77.21 s  →  71.41 s   (-7.51%)
  Au-surf ────────────────── 145.01 s  → 131.84 s   (-9.09%)
+ SiO2-ANA-kpoint-parallel ─ 169.28 s  → 133.94 s  (-20.88%)
+ SiO2-ANA-band-parallel ─── 334.82 s  → 238.47 s  (-28.78%)
```

**Comment by haampie** [comment]
Ok, so now with more aggressive restarts on top of this... I'm curious

@electronic-structure run

```yaml
reference:
  spec: sirius@6.5.7 +scalapack
current:
  spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/a2569cf</code> submitted:</summary>

```json
{
    "id": "364ccf0d-8996-4e28-a2e6-6eddfe22e4a8",
    "reference": {
        "spec": "sirius@6.5.7 +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "258836d5fa5c76a93fd859e0c659f3d24f54ca95",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 364ccf0d-8996-4e28-a2e6-6eddfe22e4a8
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/a2569cf4` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/20/258836d_vs_a24d674-a2569cf4/

```diff
  Si63Ge ───────────────────  76.99 s  →  72.28 s   (-6.11%)
+ Au-surf ────────────────── 145.92 s  → 112.69 s  (-22.78%)
+ SiO2-ANA-kpoint-parallel ─ 166.44 s  → 129.43 s  (-22.23%)
+ SiO2-ANA-band-parallel ─── 310.18 s  → 219.36 s  (-29.28%)
```

**Comment by haampie** [comment]
Let's see if the bot is still online

@electronic-structure run

```yaml
reference:
  spec: sirius@6.5.7 +scalapack
current:
  spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/853f490</code> submitted:</summary>

```json
{
    "id": "654f6877-323e-4b88-b141-b6dc2a20c0e5",
    "reference": {
        "spec": "sirius@6.5.7 +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "dd26b4c3a8b510264c2723458c0ccaf5eeca6037",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 654f6877-323e-4b88-b141-b6dc2a20c0e5
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/853f4905` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-02/11/dd26b4c_vs_a24d674-853f4905/

```diff
  Si63Ge ─────────────────── no timings available
  Au-surf ────────────────── no timings available
  SiO2-ANA-kpoint-parallel ─ no timings available
  SiO2-ANA-band-parallel ─── no timings available
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/fa2e359f` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-02/11/dd26b4c_vs_a24d674-fa2e359f/

```diff
+ Si63Ge ─────────────────── 107.99 s  →  68.63 s  (-36.45%)
- Au-surf ────────────────── 180.44 s  → 364.27 s  (+101.87%)
+ SiO2-ANA-kpoint-parallel ─ 242.64 s  → 197.38 s  (-18.65%)
+ SiO2-ANA-band-parallel ─── 1068.14 s  → 492.01 s  (-53.94%)
```

**Comment by haampie** [comment]
That looks really bad... I think it's the hyperthreading issue again. Restarted it with the same build and --exclusive flags removed.

**Comment by electronic-structure** [comment]
Report for `benchmarks/814c728d` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-02/11/dd26b4c_vs_a24d674-814c728d/

```diff
+ Si63Ge ───────────────────  77.38 s  →  48.68 s  (-37.09%)
- Au-surf ────────────────── 151.83 s  → 235.85 s  (+55.34%)
+ SiO2-ANA-kpoint-parallel ─ 169.28 s  → 122.85 s  (-27.43%)
+ SiO2-ANA-band-parallel ─── 756.38 s  → 291.66 s  (-61.44%)
```

**Comment by haampie** [comment]
The band parallel bench is slow both on master and develop compared to https://github.com/electronic-structure/SIRIUS/pull/575#issuecomment-712768992 :/

**Comment by electronic-structure** [comment]
Report for `benchmarks/a64f3fa6` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-02/11/dd26b4c_vs_a24d674-a64f3fa6/

```diff
+ Si63Ge ───────────────────  77.33 s  →  48.71 s  (-37.01%)
+ Au-surf ────────────────── 155.82 s  → 138.27 s  (-11.26%)
+ SiO2-ANA-kpoint-parallel ─ 170.21 s  → 114.60 s  (-32.67%)
+ SiO2-ANA-band-parallel ─── 770.96 s  → 297.77 s  (-61.38%)
```

**Comment by toxa81** [comment]
@electronic-structure run

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/946fd92</code> submitted:</summary>

```json
{
    "id": "119bd4aa-de8e-4210-9819-37bad5c850ea",
    "reference": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "8be4a3d847d7cac2fa4e252581562d3d44ebcb3a",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 119bd4aa-de8e-4210-9819-37bad5c850ea
```

**Comment by toxa81** [comment]
@electronic-structure run
```
reference:
  spec: sirius@6.5.7 +scalapack
current:
  spec: sirius@develop +scalapack
  ```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/d410dad</code> submitted:</summary>

```json
{
    "id": "6cf5d4cb-a00f-4daf-984a-b2ffb305558d",
    "reference": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "8be4a3d847d7cac2fa4e252581562d3d44ebcb3a",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 6cf5d4cb-a00f-4daf-984a-b2ffb305558d
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/946fd920` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-03/15/8be4a3d_vs_a24d674-946fd920/

```diff
+ Si63Ge ───────────────────  78.33 s  →  47.38 s  (-39.51%)
+ Au-surf ────────────────── 150.96 s  → 124.13 s  (-17.78%)
+ SiO2-ANA-kpoint-parallel ─ 175.75 s  → 118.34 s  (-32.67%)
  SiO2-ANA-band-parallel ─── no timings available
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/d410dad7` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-03/15/8be4a3d_vs_a24d674-d410dad7/

```diff
+ Si63Ge ───────────────────  78.77 s  →  47.18 s  (-40.11%)
+ Au-surf ────────────────── 152.06 s  → 124.43 s  (-18.17%)
+ SiO2-ANA-kpoint-parallel ─ 180.47 s  → 134.11 s  (-25.69%)
  SiO2-ANA-band-parallel ─── no timings available
```

**Comment by toxa81** [comment]
@electronic-structure run

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/3e7c45d</code> submitted:</summary>

```json
{
    "id": "cda8a8ed-268c-4aeb-807c-5f6655497d27",
    "reference": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "6f4917d65584ba2b52ea522b0bd003886a7daddd",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: cda8a8ed-268c-4aeb-807c-5f6655497d27
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/3e7c45d6` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-03/15/6f4917d_vs_a24d674-3e7c45d6/

```diff
+ Si63Ge ───────────────────  78.13 s  →  47.12 s  (-39.69%)
+ Au-surf ────────────────── 151.18 s  → 124.15 s  (-17.88%)
+ SiO2-ANA-kpoint-parallel ─ 175.45 s  → 142.52 s  (-18.77%)
  SiO2-ANA-band-parallel ─── no timings available
```

**Comment by haampie** [comment]
bors try

**Comment by toxa81** [comment]
@electronic-structure run

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/e3e5bca</code> submitted:</summary>

```json
{
    "id": "f3b3486d-a361-437f-8aea-085534a0f34c",
    "reference": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "716c74b9e40f2dc514547b13861ce8c977f50e6c",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: f3b3486d-a361-437f-8aea-085534a0f34c
```

**Comment by haampie** [comment]
I think you still have to do

@electronic-structure run

```yaml
reference:
  spec: sirius@6.5.7 +scalapack
current:
  spec: sirius@develop +scalapack
```

and make sure that the code block has valid yaml. I think last time it was somehow invalid due to whitespaces... I can make the bot complain if it is invalid yaml.

Or we should set ` variant('scalapack', default=True, ...)`

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/efd9e0a</code> submitted:</summary>

```json
{
    "id": "c2124154-600e-4d65-ad06-be94a198ec11",
    "reference": {
        "spec": "sirius@6.5.7 +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "716c74b9e40f2dc514547b13861ce8c977f50e6c",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: c2124154-600e-4d65-ad06-be94a198ec11
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/e3e5bca7` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-03/15/716c74b_vs_a24d674-e3e5bca7/

```diff
+ Si63Ge ───────────────────  77.97 s  →  47.24 s  (-39.41%)
+ Au-surf ────────────────── 151.04 s  → 124.80 s  (-17.37%)
  SiO2-ANA-kpoint-parallel ─ 182.83 s  → 164.79 s   (-9.87%)
  SiO2-ANA-band-parallel ─── no timings available
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/efd9e0ab` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-03/15/716c74b_vs_a24d674-efd9e0ab/

```diff
+ Si63Ge ───────────────────  77.01 s  →  47.40 s  (-38.45%)
+ Au-surf ────────────────── 151.65 s  → 123.92 s  (-18.28%)
+ SiO2-ANA-kpoint-parallel ─ 175.75 s  → 123.03 s  (-29.99%)
+ SiO2-ANA-band-parallel ─── 819.71 s  → 325.93 s  (-60.24%)
```

**Comment by haampie** [comment]
@electronic-structure run

```yaml
reference:
  spec: sirius@6.5.7 +scalapack
current:
  spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/ed24c61</code> submitted:</summary>

```json
{
    "id": "01cace8c-c232-482e-b31b-87f2f16250c2",
    "reference": {
        "spec": "sirius@6.5.7 +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "8d4c8fb637741d881d5cdc9faf167adefd93fb67",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 01cace8c-c232-482e-b31b-87f2f16250c2
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/ed24c61a` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-03/15/8d4c8fb_vs_a24d674-ed24c61a/

```diff
+ Si63Ge ───────────────────  77.52 s  →  47.50 s  (-38.72%)
+ Au-surf ────────────────── 150.95 s  → 124.40 s  (-17.59%)
+ SiO2-ANA-kpoint-parallel ─ 169.19 s  → 126.77 s  (-25.07%)
+ SiO2-ANA-band-parallel ─── 862.64 s  → 295.11 s  (-65.79%)
```

**Comment by haampie** [comment]
@electronic-structure run

```yaml
reference:
  spec: sirius@6.5.7 +scalapack
current:
  spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/162ebd7</code> submitted:</summary>

```json
{
    "id": "511944c9-5b86-495e-b341-d82d94cd821b",
    "reference": {
        "spec": "sirius@6.5.7 +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "a24d674330b97675090853be47ef2269f1f7185e",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "electronic-structure/SIRIUS",
        "sha": "64283b0bdde21ce92493e897e38c4105358cbbe3",
        "build": true
    },
    "report_to": {
        "repository": "electronic-structure/SIRIUS",
        "type": "pr",
        "issue": 575
    }
}

```
</details>

To trigger benchmarks again using cached binaries, include the following in your comment:
```yaml
id: 511944c9-5b86-495e-b341-d82d94cd821b
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/162ebd7e` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2021-03/15/64283b0_vs_a24d674-162ebd7e/

```diff
+ Si63Ge ───────────────────  77.30 s  →  47.30 s  (-38.81%)
+ Au-surf ────────────────── 151.07 s  → 123.61 s  (-18.17%)
+ SiO2-ANA-kpoint-parallel ─ 176.09 s  → 118.43 s  (-32.74%)
+ SiO2-ANA-band-parallel ─── 804.44 s  → 301.41 s  (-62.53%)
```

**Pull request merged**
