### PR TITLE
[WIP] revision of API functions and cleanup

### PR DESCRIPTION
**Pull request by toxa81**
As we move from the "fine grained" API to "black box" usage of SIRIUS, many API functions become unnecessary. 

TODO for this this PR:
* [x] add error codes to all functions
* [x] remove obsolete API
* [x] find_ground_state() functions must return the convergence status and may be other results
* [x] introduce types for Sim.ctx, k-point set and DFT ground state handlers
* [x] improve set/get options functions
* [x] revision of the Fortran indices: all should start from 1

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
All functions except `sirius_option_...` now have error codes. The set of `sirius_option_..` functions should be reduced. I have a proposal for that

**Comment by toxa81** [comment]
@mtaillefumier something is not right. If I run `tests/test_fortran_api` which at the beginning prints the control section, I get the following output
```
 length of control:          23
           1 cyclic_block_size           1
           2 fft_mode           3
           3 gen_evp_solver_name           3
           4 memory_usage           3
           5 mpi_grid_dims           7
           6 num_bands_to_print           1
           7 print_checksum           2
           8 print_forces           2
           9 print_hash           2
          10 print_memory_usage           2
          11 print_neighbors           2
          12 print_performance           2
          13 print_stress           2
          14 print_timers           2
          15 processing_unit           3
          16 reduce_gvec           2
          17 rmt_max           4
          18 spglib_tolerance           4
          19 std_evp_solver_name           3
          20 use_second_variation           2
          21 verbosity           1
          22 verification           1
          23           -1
          ```
          
          23 is a correct size, but `beta_chunk_size` is not printed here

**Comment by mtaillefumier** [comment]
> @mtaillefumier something is not right. If I run `tests/test_fortran_api` which at the beginning prints the control section, I get the following output
> 
> ```
>  length of control:          23
>            1 cyclic_block_size           1
>            2 fft_mode           3
>            3 gen_evp_solver_name           3
>            4 memory_usage           3
>            5 mpi_grid_dims           7
>            6 num_bands_to_print           1
>            7 print_checksum           2
>            8 print_forces           2
>            9 print_hash           2
>           10 print_memory_usage           2
>           11 print_neighbors           2
>           12 print_performance           2
>           13 print_stress           2
>           14 print_timers           2
>           15 processing_unit           3
>           16 reduce_gvec           2
>           17 rmt_max           4
>           18 spglib_tolerance           4
>           19 std_evp_solver_name           3
>           20 use_second_variation           2
>           21 verbosity           1
>           22 verification           1
>           23           -1
> ```
> 
> 23 is a correct size, but `beta_chunk_size` is not printed here

All my indices start from **zero** not **one** (because the interface is C with a fortran layer on the top of it).

**Comment by mtaillefumier** [comment]
That's perfect. Thanks.

**Comment by toxa81** [comment]
@mtaillefumier I removed `runtime_options_dictionary_` variable. We should be OK with the single config. dictionary, butt please check.  The `sirius_option_set` can now be used for all variables. Though it looks a bit ugly I can pass any type with the same arguments
```
str_val = "XC_LDA_X"
call sirius_option_set(handler, "parameters", "xc_functionals", SIRIUS_STRING_TYPE, C_LOC(str_val), len(trim(str_val)), .true.)
str_val = "XC_LDA_C_VWN"
call sirius_option_set(handler, "parameters", "xc_functionals", SIRIUS_STRING_TYPE, C_LOC(str_val), len(trim(str_val)), .true.)
```

**Comment by mtaillefumier** [comment]
they are perfectly fine the way you implemented them. can be merged

**Comment by toxa81** [comment]
bors try

**Comment by mtaillefumier** [comment]
I would suggest to remove the commented sirius_option functions. Just for cleaning up the code :)

**Pull request merged**
