### PR TITLE
Updates to the code

### PR DESCRIPTION
**Pull request by toxa81**
- band occupancies are now searched using bisection method and in parallel
- allgather interface is unified: count and offset are provided in the same order
- [WIP] documentation to the occupancy matrix

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
This is strange. I can run the tests on Daint manually and all of them pass.

**Comment by haampie** [comment]
Hm, it seems to be reproducible; fails also after restarting those band parallel tests by hand, just on test 20

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
test20 converges to a different total energy, but I think the test itself is not robust enough. So it's ok to merge

**Comment by toxa81** [comment]
bors try

**Pull request closed without merging**
