### PR TITLE
Draft: try generalized wf::inner and c++17

### PR DESCRIPTION
**Pull request by simonpintarelli**
TODO `<psi | beta> != <beta | psi> ` currently

### CODE REVIEW

**Comment by toxa81** [comment]
strane, why there are so many conflicts here

**Comment by simonpintarelli** [comment]
Let me rebase it

**Comment by toxa81** [comment]
This is my homework to re-create the base image for Daint CI/CD based on Cuda11

**Comment by toxa81** [comment]
@simonpintarelli this has probaly became obsolete

**Comment by simonpintarelli** [comment]
Yes, indeed. But perhaps we can soon require c++17?

**Pull request closed without merging**
