### PR TITLE
[WIP] Clean integration with Exciting

### PR DESCRIPTION
**Pull request by toxa81**
This API will go into their `develop` branch. Some cleanup changes break CP2K interface, so this should be fixed before merging.

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
@mtaillefumier This PR deprecates two functions from the API (`sirius_get_num_spin_components` and `sirius_get_num_bands`) and moves them to `sirius_get_parameters`. Fortran code can now do `call sirius_get_parameters(num_spins=...), call sirius_get_parameters(num_bands=...)`. This breaks CP2K interface. Can you please check when it's time to adjust CP2K and merge this PR?

**Comment by mtaillefumier** [comment]
That's fine. I can fix cp2k when I update with the latest version of SIRIUS. So you can merge it.

**Review by mtaillefumier — APPROVED** [review]

**Comment by toxa81** [comment]
bors try

**Pull request merged**
