### PR TITLE
V620

### PR DESCRIPTION
**Pull request by toxa81**
* [wip] refactoring symmetry part
* G-shells are created without floating point roundoff trick

Also, I start to convert some of the class methods into functions, especially static member functions.

### CODE REVIEW

**Comment by toxa81** [comment]
@simonpintarelli This should fix the G-shell issue

**Comment by toxa81** [comment]
@simonpintarelli I think I fixed the G-shells issue. I also changed a bit the logic in ctx::init()
The tests on my laptop pass, now I'm waiting for Jenkins CI report

**Comment by simonpintarelli** [comment]
works for me too

**Comment by simonpintarelli** [comment]
the git hash / branch is missing:
```
> $ OMP_NUM_THREADS=4 mpirun -npersocket 2 sirius.scf                                                                                    
SIRIUS 6.2.0, git hash: 
SIRIUS version : 6.2.0
git hash       : 
git branch     : 
start time     : Fri, 10 May 2019 13:22:32
```

**Pull request merged**
