### PR TITLE
add size check / simplify vec_from_str

### PR DESCRIPTION
**Pull request by simonpintarelli**
Use `std::stof`, `std::stod` in `vec_from_str`, these function throw an error if an element cannot be converted. Afaik the istream_iterator will just stop at the first non-convertible element (`std::stod` throws `std::invalid_argument`).

Also adding some cosmetic changes which were lost in the review of https://github.com/electronic-structure/SIRIUS/pull/980
- `is_upf_file`, only check last 4 characters (not the entire upf file passed as string)
- `static_cast` instead of c-style cast
- add sanity check for d_ion matrix size

### CODE REVIEW

**Comment by simonpintarelli** [comment]
cscs-ci run default

**Comment by simonpintarelli** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
@abussy I changed a bit logic for is_upf_file(). Can you please check if this version or my version is better?

**Comment by abussy** [comment]
Where can I find your version @toxa81 ?

**Comment by toxa81** [comment]
> Where can I find your version @toxa81 ?

In the merge conflict src/unit_cell/atom_type.cpp

**Comment by abussy** [comment]
> @abussy I changed a bit logic for is_upf_file(). Can you please check if this version or my version is better?

I have no strong opinion on this tbh, both implementations seem functional to me

**Comment by simonpintarelli** [comment]
@toxa81 My version avoided to check the entire string (which might be an entire UPF file of several MB).
Seems better to me to only check the last 4 characters.

**Comment by toxa81** [comment]
> @toxa81 My version avoided to check the entire string (which might be an entire UPF file of several MB). Seems better to me to only check the last 4 characters.

It was breaking for zero size input string. I didn't think of a large byte string that is not a file name.

**Comment by toxa81** [comment]
@simonpintarelli I changed is_upf_file().. hopefully for better :)

**Pull request merged**
