### PR TITLE
[WIP] magnetic GGA stress tesnsor contributio

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by haampie** [comment]
ok, i've made bors the default again, so daint ci must be triggered with `bors try` in prs, and it runs by default on develop/master

**Comment by toxa81** [comment]
This PR adds a fix for the magnetic stress tensor and GGA correction.

**Review by mtaillefumier — APPROVED** [review]
seems fine to me. :)

**Comment by toxa81** [comment]
bors try

**Comment by haampie** [comment]
btw @toxa81 you can also write `bors merge` to automatically merge after ci passes

**Comment by toxa81** [comment]
@simonpintarelli Can you approve this PR?

**Review by simonpintarelli — APPROVED** [review]
lgtm

**Pull request merged**
