### PR TITLE
Fix two more places where elpa set gpu was called

### PR DESCRIPTION
**Pull request by haampie**
And make the config of elpa the same in all solvers

### CODE REVIEW

**Comment by haampie** [comment]
@toxa81: not sure if you have had this before, but for me elpa CPU hangs in `tridiag_band` (one process hangs in mpi_wait it seems), it's hard to make a small reproducible example, since it happens after many iterations

**Comment by toxa81** [comment]
@haampie I saw this two. That's why ELPA is not our default parallel eigen-solver

**Comment by haampie** [comment]
Did you submit a ticket / email? I can make the problem go away when both SIRIUS and elpa have openmp disabled

**Comment by toxa81** [comment]
I couldn't come up with a standalone reproducer :/

**Pull request merged**
