### PR TITLE
[API] pass data back to QE

### PR DESCRIPTION
**Pull request by gsavva**
Implementation of more API functions to pass data from SIRIUS to QE:
- density matrix
- local and non-local occupation matrix

Linked to [PR#69](https://github.com/electronic-structure/q-e-sirius/pull/69) on the `q-e-sirius` side

### CODE REVIEW

**Comment by toxa81** [comment]
I have one proposal to consider: how about making a common "access" function that get/sets matrices in a single place? For example:
```
if (access == "get") {
  qe_matrix = sirius_matrix;
} else {
sirius_matrix=qe_matrix;
}
```
 and the structure of the `for` loops over l,m indices will remain the same

**Comment by gsavva** [comment]
@toxa81 thanks for the suggestion on implementing a single "access" function.
I've completed all the necessary changes, both here and in `q-e-sirius` side ([PR#69](https://github.com/electronic-structure/q-e-sirius/pull/69))
It remains to be tested thoroughly...

**Comment by gsavva** [comment]
FYI, the part for the non-local occupation matrix has a bug.
A local test, scf+U+V, runs and converges as expected but [this error](https://github.com/electronic-structure/SIRIUS/blob/feature/more_API_functions/src/api/sirius_api.cpp#L6731) is given out.
I'm investigating it...

**Comment by gsavva** [comment]
After some fixes on the q-e-sirius side, this should be good to merge.
I've done a few tests locally and the restart works in the case of scf+U+V.
@toxa81 @mtaillefumier please review this PR

**Review by toxa81 — APPROVED** [review]
looks fine

**Pull request merged**
