### PR TITLE
Hubabrd potential for LDA+U+V

### PR DESCRIPTION
**Pull request by toxa81**
Second attempt to introduce Hubbard_matrix for the Hubbard potential

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
In this merge request:
* follow the general trend - use more functions and less member functions; generate Hubbard energy and potential in this way
* use Hubbard_matrix class for the Hubbard potential; now Hubbard occupancy and potential are derived from the same class 

@mtaillefumier the stage is yours for the non-local +V correction :)

**Comment by toxa81** [comment]
bors try

**Review by mtaillefumier — APPROVED** [review]
it is good to go for me.

**Pull request merged**
