### PR TITLE
[feature] cuSolver potrf() and potri() interfaces

### PR DESCRIPTION
**Pull request by toxa81**
Warning! This requires cuda>=11.4

TODO:
 - [x] add cuda-11.4 container for the ci/cd runs on Daint

### CODE REVIEW

**Comment by mtaillefumier** [comment]
I do not think so. 11.4 is quite reasonable as a munimum required. It covers Kepler .. A100 .. grace hopper.

**Comment by simonpintarelli** [comment]
This should be fine. CUDA toolkit 11.x requires driver version >=450.80.2 (https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility), on daint the driver is 470.57. I'll add a version constrainton cuda in the spack package after this is merged.

**Comment by toxa81** [comment]
@mtaillefumier @simonpintarelli 
again, I'm doing something wrong. I rebased the branch on my local workstation, pushed the changes and now it looks like a big sum of many commits. In reality there are only three files changed.

**Comment by toxa81** [comment]
image

That should be it: a few changes on top of previous commits. All right there.

**Comment by simonpintarelli** [comment]
> image
> 
> That should be it: a few changes on top of previous commits. All right there.

Let me cherry pick these commits.

**Comment by simonpintarelli** [comment]
> I think `git push --force` should do the correct job. https://stackoverflow.com/questions/43567577/what-is-the-difference-between-force-push-and-normal-push-in-git

Agree, but I can't see the "force-pushed" tag in the PR history. Perhaps it's just too many commits to spot it.

**Comment by simonpintarelli** [comment]
I might have been too quick, what was in the `rebase` commit? I forgot to pull apparently before I did the rebase.

**Comment by toxa81** [comment]
I rebased to latest `develop` https://github.com/electronic-structure/SIRIUS/commit/2f32150f996fc889240d21a032707688bc7611e0

**Comment by toxa81** [comment]
Summary of PR:
added (but not yet used) the potrf() and potri() functions form cuSolver library.

**Comment by toxa81** [comment]
@simonpintarelli is it good to be merged?

**Review by simonpintarelli — APPROVED** [review]
lgtm

**Pull request merged**
