### PR TITLE
[enhancement] new implementation of Periodic_function class

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by electronic-structure** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
@mtaillefumier I observe a general probelem with squash commits. I rebased to develop and now I have in one single commit changes from all previous commits. Basically, if I work on a frature in a new branch, I can't rebase or merge from the base branch from which I started.

**Comment by toxa81** [comment]
I will have to close this one, start again and cherry pick the modifications that are necessary.

**Pull request closed without merging**
