### PR TITLE
[fix] Umpire allocator for the multiple device case

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
@mtaillefumier 
```
getAllocationStrategy Allocator "DEVICE0" not found. Available allocators: 
```

**Comment by mtaillefumier** [comment]
two semi-column `::` are missing. It should be "DEVICE::0" not DEVICE0

**Comment by mtaillefumier** [comment]
You were faster than me.

**Comment by toxa81** [comment]
I confirm the fix works. I can now run again on bare metal hohgant.

**Review by mtaillefumier — APPROVED** [review]

**Pull request merged**
