### PR TITLE
Matrix chat

### PR DESCRIPTION
**Pull request by simonpintarelli**
replace discourse badge by a badge for matrix channel on staffchat.ethz.ch. The discourse space has unfortunately been deleted due to inactivity. 

Preview: https://github.com/electronic-structure/SIRIUS/blob/matrix-chat/README.md

### CODE REVIEW

**Comment by RMeli** [comment]
Have you considered enabling GitHub Discussions as well/instead? I find that live chats often die down and information retrieval is difficult, while a static forum is easier to navigate and remains as a sort of a additional documentation/source of knowledge.

**Comment by simonpintarelli** [comment]
Thanks @RMeli I didn't know about github discussions. I think it wouldn't hurt to enable it. Ping @toxa81

**Comment by toxa81** [comment]
Good spot @RMeli ! I enabled discusions https://github.com/electronic-structure/SIRIUS/discussions
Matrix@ETHZ is too specific. Can you change badge, @simonpintarelli ?

**Comment by simonpintarelli** [comment]
@toxa81 the SIRIUS room in ethz staffchat is public, it can be joined by anyone with a matrix account (for example from matrix.org). I didn't manage to setup the proper shield.io badge, so I just created one with this text and a link to the space.

Or shall we replace it by a badge for slack?

**Comment by toxa81** [comment]
hmm.. they are different `green`

**Comment by simonpintarelli** [comment]
Not sure it is better. The official shields.io badge for github discussions seems to show the number of posts: https://shields.io/badges/git-hub-discussions

**Comment by simonpintarelli** [comment]
the blue is different too 😅

**Comment by toxa81** [comment]
image
looks good to me

**Comment by toxa81** [comment]
cscs-ci run default

**Pull request merged**
