### PR TITLE
touch file

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
@simonpintarelli @mtaillefumier I don't get this. Last merged PR to develop is greenlighted. All was good. I make a single character change, and this PR fails.

**Comment by toxa81** [comment]
cscs-ci run default

**Comment by simonpintarelli** [comment]
I'm getting the same diff,  clang-format removes the additional newline in `src/_header_file_template.hpp`

**Comment by toxa81** [comment]
> I'm getting the same diff, clang-format removes the additional newline in `src/_header_file_template.hpp`

yes, it's just to introduce a difference so CI can be triggered.

**Comment by simonpintarelli** [comment]
Ah ok, I was only looking at the formatting change. 

I'll try to run it locally. The unit tests are failing with SIGPIPE.

**Comment by simonpintarelli** [comment]
ok, after undoing and reapplying the whitespace commit :), it looks like a glitch with sarus which caused the PIPE error.

**Pull request closed without merging**
