### PR TITLE
for compatibility to gcc-13

### PR DESCRIPTION
**Pull request by yizeyi18**
Added #include <cstdint> to certain files for compatibility to gcc-13.

### CODE REVIEW

**Comment by toxa81** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
Dear @yizeyi18 
sorry for late repy. Can you plese do the same PR, but base it on `develop` branch.

**Comment by yizeyi18** [comment]
Dear@toxa81
Sorry, I am new to github and don't know how to change its branch. Can you help to move it?
This change is just for compatibility with gcc-13 and I missubmitted it to master branch. Sorry.

**Comment by simonpintarelli** [comment]
The develop branch doesn't need modifications, cstdint includes have been added before, it compiles with gcc13.

**Comment by yizeyi18** [comment]
> The develop branch doesn't need modifications, cstdint includes have been added before, it compiles with gcc13.

seems src/SDDK/memory.hpp had not added yet. Does it really compiles with gcc-13?
I only tried release-7.4.3 and it does not.

**Comment by simonpintarelli** [comment]
@yizeyi18 Yes, including cstdint in typedefs.hpp is enough to make it compile. 

The target branch can be changed using the `Edit` button next to the title. You would have to rebase your commits to the develop branch first.

PS: In order to be correct, cstdint would have to be included in every file where `unitX_t ` is referenced, these would be a few more according to grep.

**Pull request closed without merging**
