### PR TITLE
lmax_apw for atom type

### PR DESCRIPTION
**Pull request by toxa81**
Summary: introduce lmax_apw and Gaunt coefficients for each atom type. This brings more flexibility in how we construct the LAPW basis.

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
@simonpintarelli Hi Simon! Can you have a quick look at this PR. Nothing special, but I don't want to merge it unreviewed

**Comment by toxa81** [comment]
rocm build is suffering at the moment, this should not be a blocker.

**Review by simonpintarelli — APPROVED** [review]
looks good to me. I've change some `std::unique_ptr<>(new ...)` to `std::make_unique`.

**Pull request merged**
