### PR TITLE
Hydrogen atoms PP without beta projectors

### PR DESCRIPTION
**Pull request by mtaillefumier**
- SIRIUS will fail if we run H2 molecules with PP that have no beta projectors. The symmetrization procedure will crash in that case, so we do not symmetrize the density matrix (which is not defined in that case). I am not sure this is the right way to fix this corner case and using properly defined PP is probably better. This problem only occurs when the system only contains hydrogen atoms.

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
I did it here in a slightly different way
https://github.com/electronic-structure/SIRIUS/pull/624/commits/d1859b5c20bbb4c49c07b80e470a368307522861

The hack `std::max(1, unit_cell_.max_mt_basis_size())` is inconvenient

**Comment by toxa81** [comment]
I think this is now handled by the latest big PR

**Comment by mtaillefumier** [comment]
Ok I can close it then

**Pull request closed without merging**
