### PR TITLE
Restore computation of the hubbard contribution to the stress tensor

### PR DESCRIPTION
**Pull request by mtaillefumier**
- added an element to k_point class containing the atomic orbitals before applying S

need a better naming for the original hubbard orbitals. I can add more comments as well.

### CODE REVIEW

**Comment by toxa81** [comment]
@mtaillefumier how about naming `hubbard_atomic_wave_functions` and `hubbard_atomic_wave_functions_S` for initial atomic |phi> and S|phi> states and `hubbard_wave_functions` the final set of orbitals, participating in the Hubbard potential correction?

**Comment by toxa81** [comment]
alternatively, for the first two: `atomic_wave_functions_hub_' and 'atomic_wave_functions_S_hub_'

**Comment by mtaillefumier** [comment]
Makes a lot of sense actually.

**Comment by mtaillefumier** [comment]
I may go for the second option. It seems less confusing to me. I will make the changes.

**Comment by toxa81** [comment]
I also  like the second option more. It goes well with the notation `indexb_hub`, `inder_hub`

**Comment by mtaillefumier** [comment]
Indeed and it also tells that they are the original wfc. The other notation might confuse us saying those wfc are the one used in the computation. I will make the necessary changes and push --force to my branch.

**Pull request merged**
