### PR TITLE
Add a report of the lost time

### PR DESCRIPTION
**Pull request by toxa81**
A lost time is the time which was not measured inside the root timer.

@AdhocMan is it the right way to do it?

### CODE REVIEW

**Comment by AdhocMan** [comment]
With SIRIUS, there is a single root node, so the total time is already shown. I believe the "time lost" is the opposite of what tools like perf report as "self". Either time could be added as option to print for any node, so that in the case of SIRIUS with a single root node, you would see the desired values. It wouldn't take me much time to add this feature, if you want to go with that option.

**Comment by toxa81** [comment]
Request for enhancement then :) I'll use this opportunity. We now have this output
```
==========================================================================================================================================================
                                                                           #         Total          %   Parent %        Median           Min           Max
----------------------------------------------------------------------------------------------------------------------------------------------------------
sirius                                                                     1       35.41 s     100.00     100.00       35.41 s       35.41 s       35.41 s
 |- sirius::initialize                                                     1     207.44 ms       0.59       0.59     207.44 ms     207.44 ms     207.44 ms
 |- sirius::Simulation_context::initialize                                 1        9.34 s      26.39      26.39        9.34 s        9.34 s        9.34 s
 | |- sirius::Simulation_context::init_comm                                1       2.41 ms       0.01       0.03       2.41 ms       2.41 ms       2.41 ms
 | |- sirius::Unit_cell::initialize                                        1      74.96 ms       0.21       0.80      74.96 ms      74.96 ms      74.96 ms
 | | |- sirius::Atom_type::init                                            3      70.50 ms       0.20      94.05      25.16 ms      13.85 ms      31.50 ms
 | | |- sirius::Unit_cell::update                                          1       4.43 ms       0.01       5.91       4.43 ms       4.43 ms       4.43 ms
```

I propose to change it slightly: 1) change `|` to `+` for the 1st level nodes 2) replace % of parent time with `self` time. For (1) the report should look something like this:
```
==========================================================================================================================================================
                                                                           #         Total    Total %     self       Median           Min           Max
----------------------------------------------------------------------------------------------------------------------------------------------------------
sirius                                                                     1       35.41 s     100.00     xx       35.41 s       35.41 s       35.41 s
 +- sirius::initialize                                                     1     207.44 ms       0.59       xx     207.44 ms     207.44 ms     207.44 ms
 +- sirius::Simulation_context::initialize                                 1        9.34 s      26.39      xx        9.34 s        9.34 s        9.34 s
 | |- sirius::Simulation_context::init_comm                                1       2.41 ms       0.01       xx       2.41 ms       2.41 ms       2.41 ms
 | |- sirius::Unit_cell::initialize                                        1      74.96 ms       0.21       xx      74.96 ms      74.96 ms      74.96 ms
 | | |- sirius::Atom_type::init                                            3      70.50 ms       0.20      xx      25.16 ms      13.85 ms      31.50 ms
 | | |- sirius::Unit_cell::update                                          1       4.43 ms       0.01      xx       4.43 ms       4.43 ms       4.43 ms
```

**Comment by haampie** [comment]
What does (1) bring? Also `tree` is good inspiration, it uses `├`, `└`, `─`, `│` and reduces visual noise by showing `|`'s only when there's more children:

```
sirius                                                                     1       35.41 s     100.00     100.00       35.41 s       35.41 s       35.41 s
├── sirius::initialize                                                     1     207.44 ms       0.59       0.59     207.44 ms     207.44 ms     207.44 ms
├── sirius::Simulation_context::initialize                                 1        9.34 s      26.39      26.39        9.34 s        9.34 s        9.34 s
│   ├── sirius::Simulation_context::init_comm                              1       2.41 ms       0.01       0.03       2.41 ms       2.41 ms       2.41 ms
│   └── sirius::Unit_cell::initialize                                      1      74.96 ms       0.21       0.80      74.96 ms      74.96 ms      74.96 ms
│       ├── sirius::Atom_type::init                                        3      70.50 ms       0.20      94.05      25.16 ms      13.85 ms      31.50 ms
│       └──  sirius::Unit_cell::update                                     1       4.43 ms       0.01       5.91       4.43 ms       4.43 ms       4.43 ms
...
└──
```

**Comment by toxa81** [comment]
Well, the `+` is solely for visual recognition of the most high-level timers. Your `tree` looks even better

**Comment by AdhocMan** [comment]
I've experimented with these special characters in the past, but then one has to deal with either extended ASCII or UTF-8, which is kind of pain in C++. To use them reliably, some additional string conversions and check on the capability of the output would be required. How do you deal with this in libtree @haampie?

**Comment by AdhocMan** [comment]
After some further discussions, I'll try to use these characters and assume, that the compiler and output support UTF-8, which should be true in most cases.

**Comment by AdhocMan** [comment]
The output now looks like this:
```
=======================================================================================================================================================
                                                                        #         Total          %     Self %        Median           Min           Max
-------------------------------------------------------------------------------------------------------------------------------------------------------
sirius                                                                  1      97.58 s      100.00       0.04      97.58 s       97.58 s       97.58 s
├ sirius::initialize                                                    1      45.01 ms       0.05     100.00      45.01 ms      45.01 ms      45.01 ms
├ sirius::Simulation_context::initialize                                1     871.97 ms       0.89       0.97     871.97 ms     871.97 ms     871.97 ms
│ ├ sirius::Simulation_context::init_comm                               1       1.20 ms       0.00     100.00       1.20 ms       1.20 ms       1.20 ms
│ ├ sirius::Unit_cell::initialize                                       1      20.12 ms       0.02       0.68      20.12 ms      20.12 ms      20.12 ms
│ │ ├ sirius::Atom_type::init                                           1      17.20 ms       0.02     100.00      17.20 ms      17.20 ms      17.20 ms
│ │ └ sirius::Unit_cell::update                                         1       2.78 ms       0.00       1.22       2.78 ms       2.78 ms       2.78 ms
│ │   ├ sirius::Unit_cell::find_nearest_neighbours                      1     537.00 us       0.00     100.00     537.00 us     537.00 us     537.00 us
│ │   └ sirius::Unit_cell::get_symmetry                                 1       2.21 ms       0.00       4.44       2.21 ms       2.21 ms       2.21 ms
│ │     └ sirius::Unit_cell_symmetry                                    1       2.11 ms       0.00       6.49       2.11 ms       2.11 ms       2.11 ms
│ │       ├ sirius::Unit_cell_symmetry|spg                              1       1.76 ms       0.00     100.00       1.76 ms       1.76 ms       1.76 ms
│ │       ├ sirius::Unit_cell_symmetry|equiv                            1      78.00 us       0.00     100.00      78.00 us      78.00 us      78.00 us
│ │       └ sirius::Unit_cell_symmetry|mag                              1     139.00 us       0.00     100.00     139.00 us     139.00 us     139.00 us
│ └ sirius::Simulation_context::update                                  1     842.22 ms       0.86      10.76     842.22 ms     842.22 ms     842.22 ms
│   ├ sirius::Unit_cell::update                                         1       2.36 ms       0.00       0.38       2.36 ms       2.36 ms       2.36 ms
│   │ ├ sirius::Unit_cell::find_nearest_neighbours                      1     316.00 us       0.00     100.00     316.00 us     316.00 us     316.00 us
│   │ └ sirius::Unit_cell::get_symmetry                                 1       2.03 ms       0.00       4.04       2.03 ms       2.03 ms       2.03 ms
│   │   └ sirius::Unit_cell_symmetry                                    1       1.95 ms       0.00       5.44       1.95 ms       1.95 ms       1.95 ms
│   │     ├ sirius::Unit_cell_symmetry|spg                              1       1.60 ms       0.00     100.00       1.60 ms       1.60 ms       1.60 ms
│   │     ├ sirius::Unit_cell_symmetry|equiv                            1     119.00 us       0.00     100.00     119.00 us     119.00 us     119.00 us
│   │     └ sirius::Unit_cell_symmetry|mag                              1     127.00 us       0.00     100.00     127.00 us     127.00 us     127.00 us
│   ├ sddk::Gvec::init                                                  2     579.07 ms       0.59      52.13     289.53 ms      42.49 ms     536.58 ms
│   │ └ sddk::Gvec::find_gvec_shells                                    2     277.22 ms       0.28     100.00     138.61 ms      22.86 ms     254.36 ms
│   ├ sddk::Gvec_shells                                                 1     140.93 ms       0.14     100.00     140.93 ms     140.93 ms     140.93 ms
│   ├ sirius::Simulation_context::init_atoms_to_grid_idx                1      11.23 ms       0.01     100.00      11.23 ms      11.23 ms      11.23 ms
│   └ sirius::Simulation_context::make_periodic_function                1      18.04 ms       0.02     100.00      18.04 ms      18.04 ms      18.04 ms

```
You can select the output statistics by changing the arguments to the `print` function:
```
timing_result.print({rt_graph::Stat::Count, rt_graph::Stat::Total, rt_graph::Stat::Percentage,
                     rt_graph::Stat::SelfPercentage, rt_graph::Stat::Median, rt_graph::Stat::Min,
                     rt_graph::Stat::Max});

```
There is also new functionality now to flatten and sort the graph. For example, to reproduce the old flat timing report, one can do:
```
timing_result.flatten(1).sort_nodes().print({rt_graph::Stat::Count, rt_graph::Stat::Total, rt_graph::Stat::Percentage,
                                             rt_graph::Stat::SelfPercentage, rt_graph::Stat::Median, rt_graph::Stat::Min,
                                             rt_graph::Stat::Max});
```

**Comment by toxa81** [comment]
Looks great! What is a definition of 'self %'?

**Comment by AdhocMan** [comment]
It's the percentage of time spend in the function / timing node itself and not in any children.
These are the statistical values you can select:
```
// Selection of available statistics
enum class Stat {
  Count,             // Number of measurements
  Total,             // Total accumulated time
  Self,              // Total accumulated time minus total time of sub-timings
  Mean,              // Mean time
  Median,            // Median time
  QuartileHigh,      // Third quartile time
  QuartileLow,       // First quartile time
  Min,               // Mininum time
  Max,               // Maximum time
  Percentage,        // Percentage of accumulated time with respect to the top-level node in graph
  ParentPercentage,  // Percentage of accumulated time with respect to the parent node in graph
  SelfPercentage     // Percentage of accumulated time not spend in sub-timings
};
```

**Pull request merged**
