### PR TITLE
Add pika conflict

### PR DESCRIPTION
**Pull request by RMeli**
Add `pika` conflict to Spack package.

Related to https://github.com/pika-org/pika/pull/872 and https://github.com/pika-org/pika/pull/1017.

### CODE REVIEW

**Comment by toxa81** [comment]
cscs-ci run default

**Review by toxa81 — APPROVED** [review]
Looks fine

**Comment by toxa81** [comment]
@simonpintarelli @mtaillefumier can you please have a look?

**Review by simonpintarelli — APPROVED** [review]
lgtm

**Pull request merged**
