### PR TITLE
Remove incomplete G-vector shells

### PR DESCRIPTION
**Pull request by toxa81**
Selecting G-vectors by cutoff radius is not stable. In the rare cases we might miss the G-vectors which belong to the shell with a cutoff radius, but due to numerical noise have a slightly larger radius. In this case we are generating incomplete G-vector shell. The fix searches for the incomplete shells and removes such G-vectors.

### CODE REVIEW

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Review by mtaillefumier — APPROVED** [review]
I do not see anything wrong here. The G-vectors of a given shells are generated externally. We use symmetry to check that the present G-vectors have all their image by symmetry or delete them if not. 
The code is relevant for the outer shell but it is always good to check the inner shells as well. I would probably reject a incomplete shell all together or make it complete.

**Comment by toxa81** [comment]
Current code rejects the incomplete shell. So all the G-vectors will have length <= G_cutoff

**Pull request merged**
