### PR TITLE
[WIP] Fix magnetic symmetry

### PR DESCRIPTION
**Pull request by toxa81**
@simonpintarelli Hamiltonian is not guilty. It was a test for hermitian Hamiltonian that wasn't updated. I'm looking into collinear symmetry. Still puzzled.

### CODE REVIEW

**Comment by simonpintarelli** [comment]
The only thing I've found so far was a typo in the docstring, it should be dot(R^{-T} G, t} instead of R^{-T}*t, but in the code it is correct...

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
bors try

**Comment by toxa81** [comment]
The documentation for symmetry has been updated

image

@simonpintarelli @mtaillefumier can you have a quick look at it?

**Comment by simonpintarelli** [comment]
The rotation operator is missing in the last formula: It should be
```
    \f[
       f_{\mathrm{sym}}(R {\bf G}') = \hat{\bf S}f_{\mathrm{sym}}({\bf G})e^{-i R {\bf G'}{\bf t}}
    \f]


```

**Comment by toxa81** [comment]
I'll rewrite as matrix times G-vector everywhere

**Comment by toxa81** [comment]
Updated page

image

**Review by simonpintarelli — APPROVED** [review]
lgtm

**Pull request merged**
